package com.pedroid.qrcodecompose.androidapp.designsystem.theme

import androidx.compose.ui.graphics.Color

// Color palette created using https://m3.material.io/theme-builder#/custom
//  with primary colour #EBC248
val md_theme_dark_primary = Color(0xFFEBC248)
val md_theme_dark_onPrimary = Color(0xFF3D2F00)
val md_theme_dark_primaryContainer = Color(0xFF584400)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFE08C)
val md_theme_dark_secondary = Color(0xFFD5C5A1)
val md_theme_dark_onSecondary = Color(0xFF392F15)
val md_theme_dark_secondaryContainer = Color(0xFF50462A)
val md_theme_dark_onSecondaryContainer = Color(0xFFF2E1BB)
val md_theme_dark_tertiary = Color(0xFFADCFAE)
val md_theme_dark_onTertiary = Color(0xFF19361F)
val md_theme_dark_tertiaryContainer = Color(0xFF304D34)
val md_theme_dark_onTertiaryContainer = Color(0xFFC8ECC9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1B16)
val md_theme_dark_onBackground = Color(0xFFE8E1D9)
val md_theme_dark_surface = Color(0xFF1E1B16)
val md_theme_dark_onSurface = Color(0xFFE8E1D9)
val md_theme_dark_surfaceVariant = Color(0xFF4C4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFCFC5B4)
val md_theme_dark_outline = Color(0xFF989080)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
val md_theme_dark_inverseSurface = Color(0xFFE8E1D9)
val md_theme_dark_inversePrimary = Color(0xFF745B00)
val md_theme_dark_surfaceTint = Color(0xFFEBC248)
val md_theme_dark_outlineVariant = Color(0xFF4C4639)
val md_theme_dark_scrim = Color(0xFF000000)